### ISSUE TITLE
provide artifacts as a bundle in the form of releases

### ISSUE THREAD

**Issue by grexe** [StarLabsLtd/drivers#1]
since you will need all of the drivers anyway for a successful installation, they should be provided as a single bundle, best as a release.
This way you could also version them so it's easier to track updates.

**Comment by Sean-StarLabs** [comment]
The bundle would be too big for Git, and complicated with different versions as the drivers aren't updated at the same time and some are done via WU. We might be able to do it in the future if we can find somewhere to put them
